name: Waka Readme

on:
  push:  # This will trigger the workflow on every push to the repository
    branches:
      - main  # Assuming you want it to run on commits to the 'main' branch
  workflow_dispatch:  # This allows for manual triggering of the workflow

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Customization Flags
          SHOW_OS: "False"  # To hide OS details
          SHOW_PROJECTS: "True"  # To hide project details
          SHOW_LANGUAGE: "True"  # To show coding languages used
          SHOW_EDITORS: "False"  # To show code editors used
          SHOW_LINES_OF_CODE: "True"  # To show lines of code written
          SHOW_COMMIT: "True"  # To show commit stats
          SHOW_DAYS_OF_WEEK: "True"  # To show commits on different days of the week
          COMMIT_MESSAGE: "Updated with Dev Metrics"  # Custom commit message
          # Add more flags as needed
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"
